export const mockData = {
  data: [
    {
      login: 'ZachariBarnes',
      id: 10678967,
      node_id: 'MDQ6VXNlcjEwNjc4OTY3',
      avatar_url: 'https://avatars2.githubusercontent.com/u/10678967?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ZachariBarnes',
      html_url: 'https://github.com/ZachariBarnes',
      followers_url: 'https://api.github.com/users/ZachariBarnes/followers',
      following_url:
            'https://api.github.com/users/ZachariBarnes/following{/other_user}',
      gists_url: 'https://api.github.com/users/ZachariBarnes/gists{/gist_id}',
      starred_url:
            'https://api.github.com/users/ZachariBarnes/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ZachariBarnes/subscriptions',
      organizations_url: 'https://api.github.com/users/ZachariBarnes/orgs',
      repos_url: 'https://api.github.com/users/ZachariBarnes/repos',
      events_url:
            'https://api.github.com/users/ZachariBarnes/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ZachariBarnes/received_events',
      type: 'User',
      site_admin: false,
    },
    {
      login: 'FurqanM',
      id: 1145666,
      node_id: 'MDQ6VXNlcjExNDU2NjY=',
      avatar_url: 'https://avatars2.githubusercontent.com/u/1145666?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/FurqanM',
      html_url: 'https://github.com/FurqanM',
      followers_url: 'https://api.github.com/users/FurqanM/followers',
      following_url: 'https://api.github.com/users/FurqanM/following{/other_user}',
      gists_url: 'https://api.github.com/users/FurqanM/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/FurqanM/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/FurqanM/subscriptions',
      organizations_url: 'https://api.github.com/users/FurqanM/orgs',
      repos_url: 'https://api.github.com/users/FurqanM/repos',
      events_url: 'https://api.github.com/users/FurqanM/events{/privacy}',
      received_events_url: 'https://api.github.com/users/FurqanM/received_events',
      type: 'User',
      site_admin: false,
    },
    {
      login: 'iphipps',
      id: 2248979,
      node_id: 'MDQ6VXNlcjIyNDg5Nzk=',
      avatar_url: 'https://avatars0.githubusercontent.com/u/2248979?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/iphipps',
      html_url: 'https://github.com/iphipps',
      followers_url: 'https://api.github.com/users/iphipps/followers',
      following_url: 'https://api.github.com/users/iphipps/following{/other_user}',
      gists_url: 'https://api.github.com/users/iphipps/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/iphipps/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/iphipps/subscriptions',
      organizations_url: 'https://api.github.com/users/iphipps/orgs',
      repos_url: 'https://api.github.com/users/iphipps/repos',
      events_url: 'https://api.github.com/users/iphipps/events{/privacy}',
      received_events_url: 'https://api.github.com/users/iphipps/received_events',
      type: 'User',
      site_admin: false,
    },
    {
      login: 'alixaxel',
      id: 262782,
      node_id: 'MDQ6VXNlcjI2Mjc4Mg==',
      avatar_url: 'https://avatars2.githubusercontent.com/u/262782?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alixaxel',
      html_url: 'https://github.com/alixaxel',
      followers_url: 'https://api.github.com/users/alixaxel/followers',
      following_url: 'https://api.github.com/users/alixaxel/following{/other_user}',
      gists_url: 'https://api.github.com/users/alixaxel/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/alixaxel/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/alixaxel/subscriptions',
      organizations_url: 'https://api.github.com/users/alixaxel/orgs',
      repos_url: 'https://api.github.com/users/alixaxel/repos',
      events_url: 'https://api.github.com/users/alixaxel/events{/privacy}',
      received_events_url: 'https://api.github.com/users/alixaxel/received_events',
      type: 'User',
      site_admin: false,
    },
    {
      login: 'pe-aps24',
      id: 6762078,
      node_id: 'MDQ6VXNlcjY3NjIwNzg=',
      avatar_url: 'https://avatars3.githubusercontent.com/u/6762078?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/pe-aps24',
      html_url: 'https://github.com/pe-aps24',
      followers_url: 'https://api.github.com/users/pe-aps24/followers',
      following_url: 'https://api.github.com/users/pe-aps24/following{/other_user}',
      gists_url: 'https://api.github.com/users/pe-aps24/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/pe-aps24/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/pe-aps24/subscriptions',
      organizations_url: 'https://api.github.com/users/pe-aps24/orgs',
      repos_url: 'https://api.github.com/users/pe-aps24/repos',
      events_url: 'https://api.github.com/users/pe-aps24/events{/privacy}',
      received_events_url: 'https://api.github.com/users/pe-aps24/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
};
export default mockData;
